---
- name: Build and Publish Docker Image
  hosts: webserver
  gather_facts: false

  tasks:
    - name: Build Docker Image
      command: docker build -t mallieswari/abctechnologies-latest-with-ansible -f /opt/ABC\ Technologies/Dockerfile /root/jenkins/workspace/ABC-Technologies-CICD

    - name: Log in to Docker Hub
      shell: echo "{{ docker_password }}" | docker login -u "{{ docker_username }}" --password-stdin
      register: docker_login_result
      ignore_errors: yes

    - name: Push to Docker Hub
      shell: docker push mallieswari/abctechnologies-latest-with-ansible
      when: docker_login_result.rc == 0

